<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xgc.rag</groupId>
    <artifactId>hello-rag-agent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>hello-rag-agent</name>
    <packaging>pom</packaging>
    <description>backend</description>

    <modules>
        <module>fw-base</module>
        <module>app</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <!--spring-boot版本-->
        <spring-boot.version>3.5.7</spring-boot.version>
        <!--hutool版本-->
        <hutool-all.version>5.8.37</hutool-all.version>
        <!--mybatis-plus版本-->
        <mybatis-plus-spring-boot3-starter.version>3.5.17</mybatis-plus-spring-boot3-starter.version>
        <!--pgvector版本-->
        <pgvector.version>0.1.6</pgvector.version>
        <!--redis相关配置-->
        <sa-token.version>1.43.0</sa-token.version>
        <redisson.version>4.0.0</redisson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--spring-boot统一管理依赖版本-->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <!--引入的是一个 POM 清单，不是普通 jar-->
                <type>pom</type>
                <!--把这份清单里的版本管理「合并」进当前项目的 dependencyManagement-->
                <scope>import</scope>
            </dependency>

            <!--hutool依赖 start-->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool-all.version}</version>
            </dependency>
            <!--hutool依赖 start-->

            <!--mybatis-plus依赖 start-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus-spring-boot3-starter.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-jsqlparser</artifactId>
                <version>${mybatis-plus-spring-boot3-starter.version}</version>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus-spring-boot3-starter.version}</version>
            </dependency>
            <!--mybatis-plus依赖 end-->

            <!--redis依赖 start-->
            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-spring-boot3-starter</artifactId>
                <version>${sa-token.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-redis-template</artifactId>
                <version>${sa-token.version}</version>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <!--redis依赖 start-->
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!--lombok依赖 start-->
        <!--spring-boot-dependencies中包含了lombok版本，所以这里不用单独配置-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <!--lombok依赖 end-->

        <!--junit test依赖 start-->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <!--junit test依赖 end-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
