<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xgc.rag</groupId>
        <artifactId>Hello-AgentR</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>app</artifactId>

    <dependencies>
        <!--fw-base start-->
        <dependency>
            <groupId>com.xgc.rag</groupId>
            <artifactId>fw-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!--fw-base start-->

        <!--web容器依赖 start-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--web容器依赖 end-->

        <!--Postgres start-->
        <!-- Postgres JDBC驱动（基础） -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <!-- pgvector自定义向量类型支持 -->
        <dependency>
            <groupId>com.pgvector</groupId>
            <artifactId>pgvector</artifactId>
            <version>${pgvector.version}</version>
        </dependency>
        <!--Postgres end-->

        <!-- Mybatis-plus代码生成器（仅开发/测试阶段使用，不进入正式包） -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Mybatis-plus代码生成器（仅开发/测试阶段使用，不进入正式包） -->

        <!--参数校验-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <!--参数校验-->

        <!-- 密码哈希（BCrypt）；仅 crypto，不引入 spring-security-web -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
        <!-- 密码哈希（BCrypt）；仅 crypto，不引入 spring-security-web -->

        <!-- tika用于文档解析，支持PPT / XLS / PDF / DOC / DOCX / Markdown  start-->
        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-parsers-standard-package</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-core</artifactId>
        </dependency>
        <!-- tika用于文档解析，支持PPT / XLS / PDF / DOC / DOCX / Markdown  end-->

    </dependencies>
</project>
